/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum2;

/**
 *
 * @author Rara ^___^
 */
public class praktikum extends javax.swing.JFrame {
    String jns ="";
    int jml;
    /**
     * Creates new form praktikum
     */
    public praktikum() {
        initComponents();
        getJumlah();
        setJenis();
        panel.setVisible(false);
        pil.setVisible(true);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();
        ket = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pil = new javax.swing.JComboBox<>();
        bil1 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        bil2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        bil4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Program Aritmatika");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 140, 30);

        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 90, 20);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih---", "Penjumlahan", "Pengurangan", "Pembagian", "Perkalian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(180, 60, 120, 30);

        panel.setBackground(new java.awt.Color(153, 204, 255));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi"));
        panel.setLayout(null);
        panel.add(ket);
        ket.setBounds(120, 20, 90, 20);

        jLabel5.setText("Jumlah bilangan");
        panel.add(jLabel5);
        jLabel5.setBounds(20, 60, 110, 20);

        pil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----pilih---", "2", "3", "4" }));
        pil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilActionPerformed(evt);
            }
        });
        panel.add(pil);
        pil.setBounds(160, 60, 130, 20);

        bil1.setText("Bilangan 1");
        panel.add(bil1);
        bil1.setBounds(20, 90, 90, 20);
        panel.add(b1);
        b1.setBounds(160, 90, 130, 30);
        panel.add(b2);
        b2.setBounds(160, 130, 130, 30);
        panel.add(b3);
        b3.setBounds(160, 170, 130, 30);
        panel.add(b4);
        b4.setBounds(160, 210, 130, 30);

        bil2.setText("Bilangan 2");
        panel.add(bil2);
        bil2.setBounds(20, 130, 90, 20);

        bil3.setText("Bilangan 3");
        panel.add(bil3);
        bil3.setBounds(20, 170, 90, 20);

        bil4.setText("Bilangan 4");
        panel.add(bil4);
        bil4.setBounds(20, 210, 90, 20);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1);
        jButton1.setBounds(180, 250, 80, 30);
        panel.add(hasil);
        hasil.setBounds(160, 290, 130, 70);

        getContentPane().add(panel);
        panel.setBounds(40, 110, 330, 380);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 410, 510);

        setBounds(0, 0, 423, 552);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed

    public void setJenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns="Penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            pil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pengurangan")){
            jns="Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            pil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pembagian")){
            jns="Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            pil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Perkalian")){
            jns="Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            pil.setEnabled(true);
        }
    } 
    
    private void pilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_pilActionPerformed

    public void getJumlah(){
        if(pil.getSelectedItem().equals("2")){
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml=2;
        }
        else if(pil.getSelectedItem().equals("3")){
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml=3;
        }
        else if(pil.getSelectedItem().equals("4")){
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml=4;
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double hsl=0.0;
        double a1,a2,a3,a4;
        a1=Double.parseDouble(b1.getText().toString());
        a2=Double.parseDouble(b2.getText().toString());
        a3=Double.parseDouble(b3.getText().toString());
        a4=Double.parseDouble(b4.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml==2){
                hsl=a1+a2;
                hasil.setText(""+a1+"+"+a2+"="+hsl);
            }
            if(jml==3){
                hsl=a1+a2+a3;
                hasil.setText(""+a1+"+"+a2+"+"+a3+"="+hsl);
            }
            if(jml==4){
                hsl=a1+a2+a3+a4;
                hasil.setText(""+a1+"+"+a2+"+"+a3+"+"+a4+"="+hsl);
            }
        }
        else if(jns.equals("Pengurangan")){
            if(jml==2){
                hsl=a1-a2;
                hasil.setText(""+a1+"-"+a2+"="+hsl);
            }
            if(jml==3){
                hsl=a1-a2-a3;
                hasil.setText(""+a1+"-"+a2+"-"+a3+"="+hsl);
            }
            if(jml==4){
                hsl=a1-a2-a3-a4;
                hasil.setText(""+a1+"-"+a2+"-"+a3+"-"+a4+"="+hsl);
            }
        }
        else if(jns.equals("Pembagian")){
            if(jml==2){
                hsl=a1/a2;
                hasil.setText(""+a1+":"+a2+"="+hsl);
            }
            if(jml==3){
                hsl=a1/a2/a3;
                hasil.setText(""+a1+":"+a2+":"+a3+"="+hsl);
            }
            if(jml==4){
                hsl=a1/a2/a3/a4;
                hasil.setText(""+a1+":"+a2+":"+a3+":"+a4+"="+hsl);
            }
        else if(jns.equals("Perkalian")){
            if(jml==2){
                hsl=a1*a2;
                hasil.setText(""+a1+"*"+a2+"="+hsl);
            }
            if(jml==3){
                hsl=a1*a2*a3;
                hasil.setText(""+a1+"*"+a2+"*"+a3+"="+hsl);
            }
            if(jml==4){
                hsl=a1*a2*a3*a4;
                hasil.setText(""+a1+"*"+a2+"*"+a3+"*"+a4+"="+hsl);
            }
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new praktikum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pil;
    // End of variables declaration//GEN-END:variables
}
